name: Random GIF Updater

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Manual trigger

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python for random GIF selection
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install necessary libraries
      - name: Install required libraries
        run: |
          pip install requests

      # Fetch a random GIF from your set of GIF URLs and update the README
      - name: Update README with random GIF
        run: |
          import random
          import requests

          # List of Giphy URLs
          gifs = [
            "https://media.giphy.com/media/Rbst7XSD9K2dsazQTE/giphy.gif",
            "https://media.giphy.com/media/JU18ab3BRw4ok/giphy.gif",
            "https://media.giphy.com/media/26gslXKhYZd6pAkl6/giphy.gif"
            # Add more GIFs as needed
          ]

          # Pick a random GIF
          selected_gif = random.choice(gifs)

          # Read the current README.md file
          with open("README.md", "r") as file:
            readme_content = file.read()

          # Replace the placeholder with the selected GIF
          updated_content = readme_content.replace(
              "![GIF](https://media.giphy.com/media/Rbst7XSD9K2dsazQTE/giphy.gif)",
              f"![GIF]({selected_gif})"
          )

          # Write the updated content back to the README
          with open("README.md", "w") as file:
            file.write(updated_content)

      # Commit the changes back to the repository
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update GIF in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
