name: GitHub Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up cache to avoid re-generating if no changes
      - name: Cache dist directory
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-

      # Step 3: Generate the snake animations with dynamic colors and shapes
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Specify the year for the contributions (e.g., 2023)
          year: 2023  # <-- Specify the year here
          # Randomize the snake color and shape (circle or square)
          outputs: |
            dist/github-snake.svg?color_snake=random&shape=random  # Randomize color and shape
            dist/github-snake-dark.svg?palette=github-dark&color_snake=random&shape=random
            dist/ocean.gif?color_snake=random&color_dots=random
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Deploy to Output Branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Dynamically generate the commit message with the current date
          commit_message: "Update snake animation for $(date +'%Y-%m-%d') [skip ci]"
